// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Teretana.Api.Podaci;

#nullable disable

namespace Teretana.Api.Podaci.Migracije
{
    [DbContext(typeof(TeretanaDbContext))]
    [Migration("20260913233122_Pocetna")]
    partial class Pocetna
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("Teretana.Api.Domen.Korisnik", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<string>("ImePrezime")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("KreiranAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("LozinkaHash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Uloga")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Korisnici", null, t =>
                        {
                            t.HasCheckConstraint("CK_Korisnici_Uloga", "\"Uloga\" IN ('Clan', 'Trener')");
                        });
                });

            modelBuilder.Entity("Teretana.Api.Domen.Rezervacija", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClanId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("KreiranaAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("OtkazanaAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("PotvrdjenaAt")
                        .HasColumnType("TEXT");

                    b.Property<bool?>("Prisustvovao")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("TerminId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ClanId");

                    b.HasIndex("TerminId", "ClanId")
                        .IsUnique()
                        .HasDatabaseName("UX_Rezervacije_AktivnaPrijava")
                        .HasFilter("\"Status\" IN ('Potvrdjena', 'NaCekanju')");

                    b.HasIndex("TerminId", "Status", "KreiranaAt", "Id")
                        .HasDatabaseName("IX_Rezervacije_RedCekanja");

                    b.ToTable("Rezervacije", null, t =>
                        {
                            t.HasCheckConstraint("CK_Rezervacije_Status", "\"Status\" IN ('Potvrdjena', 'NaCekanju', 'Otkazana')");
                        });
                });

            modelBuilder.Entity("Teretana.Api.Domen.Termin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BrojPotvrdjenih")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Kapacitet")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Kraj")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("KreiranAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Opis")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Pocetak")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("TrenerId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Pocetak");

                    b.HasIndex("TrenerId");

                    b.ToTable("Termini", null, t =>
                        {
                            t.HasCheckConstraint("CK_Termini_BrojPotvrdjenih", "\"BrojPotvrdjenih\" >= 0 AND \"BrojPotvrdjenih\" <= \"Kapacitet\"");

                            t.HasCheckConstraint("CK_Termini_Kapacitet", "\"Kapacitet\" > 0");

                            t.HasCheckConstraint("CK_Termini_KrajPoslePocetka", "\"Kraj\" > \"Pocetak\"");

                            t.HasCheckConstraint("CK_Termini_Status", "\"Status\" IN ('Aktivan', 'Otkazan')");
                        });
                });

            modelBuilder.Entity("Teretana.Api.Domen.Rezervacija", b =>
                {
                    b.HasOne("Teretana.Api.Domen.Korisnik", "Clan")
                        .WithMany()
                        .HasForeignKey("ClanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Teretana.Api.Domen.Termin", "Termin")
                        .WithMany("Rezervacije")
                        .HasForeignKey("TerminId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Clan");

                    b.Navigation("Termin");
                });

            modelBuilder.Entity("Teretana.Api.Domen.Termin", b =>
                {
                    b.HasOne("Teretana.Api.Domen.Korisnik", "Trener")
                        .WithMany()
                        .HasForeignKey("TrenerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Trener");
                });

            modelBuilder.Entity("Teretana.Api.Domen.Termin", b =>
                {
                    b.Navigation("Rezervacije");
                });
#pragma warning restore 612, 618
        }
    }
}
